/*
 * TR Timeline Widget — data
 *
 * This is the file to edit. It is plain data (JSON) wrapped in a single line so
 * it loads as a <script> — the timeline works whether you open the page from
 * disk, serve it locally, or embed it on another site.
 *
 * To ADD A POINT, copy a line in "events" (Roosevelt) or "history" (U.S./world)
 * and change the values. Fields:
 *   year   — the calendar year (required)
 *   date   — precise date; also sets the exact horizontal position, so events
 *            in the same year spread out in a zoomed-in embed (optional)
 *   label  — the short on-line caption
 *   weight — 1–5 (decimals allowed, e.g. 2.5); higher weights survive when
 *            space is tight, so use finer values to rank within a tier
 *   blurb  — the sentence shown on hover/click
 *   link   — (events/phases) a trlibrary.com page; adds an "Explore" button
 *   accent — true for the orange highlight on a phase bar
 *
 * Dates are grounded in the Theodore Roosevelt Association day-by-day
 * chronology; verify against trlibrary.com/gpt before publication.
 */
window.TRTimelineData = {
  "subject": "Theodore Roosevelt",
  "born": 1858,
  "died": 1919,

  "phases": [
    { "id": "early", "label": "Early Life", "start": 1858, "end": 1883, "fill": "#99ADC5", "ink": "#14212e",
      "link": "https://www.trlibrary.com/tr/early-life",
      "blurb": "A sickly, asthmatic boy born in New York City in 1858 who built his body and his will through what he later called the strenuous life." },
    { "id": "badlands", "label": "The Badlands", "start": 1883, "end": 1887, "fill": "#D1CCBD", "ink": "#25282A", "accent": true,
      "link": "https://www.trlibrary.com/tr/badlands",
      "blurb": "After losing his wife and his mother on the same day, Roosevelt came west to ranch and hunt in the Dakota Badlands — the country that shaped him." },
    { "id": "rise", "label": "Rise to Power", "start": 1887, "end": 1901, "fill": "#8FC895", "ink": "#16311f",
      "link": "https://www.trlibrary.com/tr/rise-to-power",
      "blurb": "Civil Service reformer, New York City police commissioner, Assistant Secretary of the Navy, Rough Rider, and Governor of New York." },
    { "id": "presidency", "label": "Presidency", "start": 1901, "end": 1909, "fill": "#092A4D", "ink": "#ffffff",
      "link": "https://www.trlibrary.com/tr/presidency",
      "blurb": "The nation's 26th president. The Square Deal, trust-busting, the Panama Canal, and the broadest conservation record of any president." },
    { "id": "post", "label": "Post-Presidency", "start": 1909, "end": 1919, "fill": "#1B4532", "ink": "#ffffff",
      "link": "https://www.trlibrary.com/tr/post-presidency",
      "blurb": "An African expedition, the Bull Moose campaign of 1912, and a near-fatal journey down the Amazon's River of Doubt." }
  ],

  "events": [
    { "year": 1858, "date": "October 27, 1858", "label": "Born", "weight": 5, "link": "https://www.trlibrary.com/tr/early-life",
      "blurb": "Theodore Roosevelt Jr. is born in Manhattan at 7:45 p.m. — a sickly, asthmatic child who will remake himself through sheer will." },
    { "year": 1865, "date": "April 1865", "label": "Lincoln's funeral", "weight": 2, "link": "https://www.trlibrary.com/tr/early-life",
      "blurb": "Six-year-old Theodore watches Lincoln's funeral procession pass his grandfather's house in New York." },
    { "year": 1867, "date": "1867", "label": "Starts a museum", "weight": 2, "link": "https://www.trlibrary.com/tr/early-life",
      "blurb": "Founds the “Roosevelt Museum of Natural History” in his bedroom, cataloguing specimens like a young naturalist." },
    { "year": 1869, "date": "1869", "label": "Grand Tour", "weight": 2, "link": "https://www.trlibrary.com/tr/early-life",
      "blurb": "The Roosevelt family sets out on a year-long tour of Europe." },
    { "year": 1870, "date": "1870", "label": "Builds his body", "weight": 2, "link": "https://www.trlibrary.com/tr/early-life",
      "blurb": "Told to “make his body,” the frail boy takes up boxing and gymnastics in a home gym." },
    { "year": 1872, "date": "1872", "label": "Egypt and the Nile", "weight": 2, "link": "https://www.trlibrary.com/tr/early-life",
      "blurb": "A family voyage up the Nile; young Theodore, given a gun and spectacles, takes up birding and taxidermy." },
    { "year": 1873, "date": "1873", "label": "Studies in Germany", "weight": 2, "link": "https://www.trlibrary.com/tr/early-life",
      "blurb": "Lives and studies with a family in Dresden, Germany, soaking up languages and literature." },
    { "year": 1876, "date": "1876", "label": "Enters Harvard", "weight": 3, "link": "https://www.trlibrary.com/tr/early-life",
      "blurb": "Enrolls at Harvard College." },
    { "year": 1878, "date": "February 1878", "label": "Father dies", "weight": 3, "link": "https://www.trlibrary.com/tr/early-life",
      "blurb": "Theodore Roosevelt Sr., his hero and moral compass, dies while Theodore is at Harvard." },
    { "year": 1878, "date": "October 1878", "label": "Meets Alice Lee", "weight": 2, "link": "https://www.trlibrary.com/tr/early-life",
      "blurb": "Meets Alice Hathaway Lee and is instantly smitten." },
    { "year": 1880, "date": "June 1880", "label": "Graduates Harvard", "weight": 3, "link": "https://www.trlibrary.com/tr/early-life",
      "blurb": "Graduates Harvard magna cum laude." },
    { "year": 1880, "date": "October 27, 1880", "label": "Marries Alice", "weight": 3, "link": "https://www.trlibrary.com/tr/early-life",
      "blurb": "Marries Alice Hathaway Lee on his 22nd birthday." },
    { "year": 1880, "date": "November 1880", "label": "Enters Columbia Law", "weight": 2, "link": "https://www.trlibrary.com/tr/early-life",
      "blurb": "Begins law school at Columbia, though politics soon pulls him away." },
    { "year": 1881, "date": "November 1881", "label": "Enters politics", "weight": 3, "link": "https://www.trlibrary.com/tr/rise-to-power",
      "blurb": "Elected to the New York State Assembly at 23 — its youngest member." },
    { "year": 1882, "date": "January 1882", "label": "Takes Assembly seat", "weight": 2, "link": "https://www.trlibrary.com/tr/rise-to-power",
      "blurb": "Takes his seat in Albany and quickly makes a name as a reformer." },
    { "year": 1882, "date": "1882", "label": "First book", "weight": 2, "link": "https://www.trlibrary.com/tr/early-life",
      "blurb": "Publishes “The Naval War of 1812,” a serious work of history at 23." },
    { "year": 1883, "date": "September 1883", "label": "First trip West", "weight": 4, "link": "https://www.trlibrary.com/tr/badlands",
      "blurb": "Travels to the Dakota Badlands to hunt bison and buys into the Maltese Cross Ranch." },
    { "year": 1884, "date": "February 12, 1884", "label": "Daughter born", "weight": 2, "link": "https://www.trlibrary.com/tr/badlands",
      "blurb": "His daughter Alice is born — two days before tragedy strikes the family." },
    { "year": 1884, "date": "February 14, 1884", "label": "Double tragedy", "weight": 5, "link": "https://www.trlibrary.com/tr/badlands",
      "blurb": "His wife Alice and his mother Mittie die in the same house on the same day — the loss that sends him west." },
    { "year": 1884, "date": "June 1884", "label": "GOP convention", "weight": 2, "link": "https://www.trlibrary.com/tr/rise-to-power",
      "blurb": "Serves as a delegate to the Republican National Convention, an early turn on the national stage." },
    { "year": 1884, "date": "August 1884", "label": "Elkhorn Ranch", "weight": 3, "link": "https://www.trlibrary.com/tr/badlands",
      "blurb": "Establishes the Elkhorn Ranch on the Little Missouri River, his refuge and second Dakota home." },
    { "year": 1885, "date": "1885", "label": "Publishes ranch book", "weight": 2, "link": "https://www.trlibrary.com/tr/badlands",
      "blurb": "Publishes “Hunting Trips of a Ranchman,” the first of his Badlands books." },
    { "year": 1886, "date": "March 1886", "label": "Captures boat thieves", "weight": 3, "link": "https://www.trlibrary.com/tr/badlands",
      "blurb": "As a deputy sheriff, chases three boat thieves down the ice-choked Little Missouri and marches them to justice." },
    { "year": 1886, "date": "November 1886", "label": "Runs for mayor", "weight": 2, "link": "https://www.trlibrary.com/tr/rise-to-power",
      "blurb": "Runs for mayor of New York City and finishes third." },
    { "year": 1886, "date": "December 2, 1886", "label": "Marries Edith", "weight": 3, "link": "https://www.trlibrary.com/tr/badlands",
      "blurb": "Marries his childhood friend Edith Kermit Carow in London." },
    { "year": 1887, "date": "1887", "label": "Winter ruins his herd", "weight": 3, "link": "https://www.trlibrary.com/tr/badlands",
      "blurb": "The brutal winter of 1886–87 kills much of his cattle and effectively ends his ranching venture." },
    { "year": 1887, "date": "December 1887", "label": "Boone & Crockett Club", "weight": 3, "link": "https://www.trlibrary.com/tr/conservation",
      "blurb": "Co-founds the Boone and Crockett Club with George Bird Grinnell to champion big-game conservation." },
    { "year": 1888, "date": "1888", "label": "Ranch Life book", "weight": 2, "link": "https://www.trlibrary.com/tr/badlands",
      "blurb": "Publishes “Ranch Life and the Hunting-Trail,” illustrated by Frederic Remington." },
    { "year": 1888, "date": "October 1888", "label": "Stumps for Harrison", "weight": 2, "link": "https://www.trlibrary.com/tr/rise-to-power",
      "blurb": "Campaigns for Benjamin Harrison's presidential run." },
    { "year": 1889, "date": "May 1889", "label": "Civil Service reform", "weight": 2, "link": "https://www.trlibrary.com/tr/rise-to-power",
      "blurb": "Appointed U.S. Civil Service Commissioner, taking on the spoils system." },
    { "year": 1889, "date": "1889", "label": "Winning of the West", "weight": 2, "link": "https://www.trlibrary.com/tr/rise-to-power",
      "blurb": "Begins publishing “The Winning of the West,” his sweeping history of the frontier." },
    { "year": 1895, "date": "1895", "label": "NYC Police Board", "weight": 2, "link": "https://www.trlibrary.com/tr/rise-to-power",
      "blurb": "Becomes president of the New York City Police Board and shakes up a corrupt force." },
    { "year": 1896, "date": "1896", "label": "Campaigns for McKinley", "weight": 2, "link": "https://www.trlibrary.com/tr/rise-to-power",
      "blurb": "Stumps hard for William McKinley's presidential campaign." },
    { "year": 1897, "date": "1897", "label": "Assistant Navy Sec.", "weight": 2, "link": "https://www.trlibrary.com/tr/rise-to-power",
      "blurb": "Serves as Assistant Secretary of the Navy, pushing to modernize the fleet." },
    { "year": 1898, "date": "May 1898", "label": "Forms Rough Riders", "weight": 3, "link": "https://www.trlibrary.com/tr/rise-to-power",
      "blurb": "Resigns from the Navy Department to raise and lead the Rough Riders." },
    { "year": 1898, "date": "June 1898", "label": "Las Guásimas", "weight": 2, "link": "https://www.trlibrary.com/tr/rise-to-power",
      "blurb": "Sees his first combat as the Rough Riders fight at Las Guásimas in Cuba." },
    { "year": 1898, "date": "July 1, 1898", "label": "San Juan Heights", "weight": 4, "link": "https://www.trlibrary.com/tr/rise-to-power",
      "blurb": "Leads the charge up the San Juan Heights — “the great day of my life” — becoming a national hero." },
    { "year": 1898, "date": "September 1898", "label": "Mustered out", "weight": 2, "link": "https://www.trlibrary.com/tr/rise-to-power",
      "blurb": "The Rough Riders disband at Montauk; Roosevelt returns home a celebrity." },
    { "year": 1898, "date": "November 1898", "label": "Elected Governor", "weight": 3, "link": "https://www.trlibrary.com/tr/rise-to-power",
      "blurb": "Rides his war fame to election as governor of New York." },
    { "year": 1899, "date": "April 1899", "label": "Strenuous Life", "weight": 3, "link": "https://www.trlibrary.com/tr/rise-to-power",
      "blurb": "In Chicago he preaches “the strenuous life” — the doctrine of effort and daring that defines him." },
    { "year": 1900, "date": "November 1900", "label": "Elected Vice President", "weight": 3, "link": "https://www.trlibrary.com/tr/rise-to-power",
      "blurb": "Elected vice president on the ticket with William McKinley." },
    { "year": 1901, "date": "September 2, 1901", "label": "“Big stick”", "weight": 3, "link": "https://www.trlibrary.com/tr/rise-to-power",
      "blurb": "At the Minnesota State Fair he sums up his creed: “Speak softly and carry a big stick.”" },
    { "year": 1901, "date": "September 14, 1901", "label": "Becomes President", "weight": 5, "link": "https://www.trlibrary.com/tr/presidency",
      "blurb": "Sworn in after McKinley's assassination — the youngest person ever to become president." },
    { "year": 1902, "date": "June 1902", "label": "Reclamation Act", "weight": 3, "link": "https://www.trlibrary.com/tr/conservation",
      "blurb": "Signs the Newlands Reclamation Act, funding irrigation and dams across the arid West." },
    { "year": 1902, "date": "October 1902", "label": "Coal strike settled", "weight": 3, "link": "https://www.trlibrary.com/tr/presidency",
      "blurb": "Forces mine owners and workers to arbitrate the anthracite coal strike — a landmark Square Deal moment." },
    { "year": 1902, "date": "November 1902", "label": "The Teddy Bear", "weight": 3, "link": "https://www.trlibrary.com/tr/legacy",
      "blurb": "On a Mississippi hunt he refuses to shoot a captured bear; a cartoon gives rise to the “Teddy Bear.”" },
    { "year": 1903, "date": "March 14, 1903", "label": "Pelican Island", "weight": 3, "link": "https://www.trlibrary.com/tr/conservation",
      "blurb": "Establishes Pelican Island, Florida, as the first federal bird reservation." },
    { "year": 1903, "date": "May 1903", "label": "Camps with Muir", "weight": 3, "link": "https://www.trlibrary.com/tr/conservation",
      "blurb": "Spends three nights camping with John Muir in Yosemite, sealing his conservation resolve." },
    { "year": 1904, "date": "November 1904", "label": "Elected president", "weight": 4, "link": "https://www.trlibrary.com/tr/presidency",
      "blurb": "Wins the presidency in his own right in a landslide." },
    { "year": 1904, "date": "December 1904", "label": "Roosevelt Corollary", "weight": 2, "link": "https://www.trlibrary.com/tr/presidency",
      "blurb": "Adds his Corollary to the Monroe Doctrine, asserting U.S. authority in the Americas." },
    { "year": 1905, "date": "February 1905", "label": "Forest Service", "weight": 3, "link": "https://www.trlibrary.com/tr/conservation",
      "blurb": "Transfers the national forests to a new U.S. Forest Service under Gifford Pinchot." },
    { "year": 1905, "date": "September 1905", "label": "Treaty of Portsmouth", "weight": 3, "link": "https://www.trlibrary.com/tr/presidency",
      "blurb": "Mediates the treaty ending the Russo-Japanese War, brokered in New Hampshire." },
    { "year": 1906, "date": "February 1906", "label": "Alice's wedding", "weight": 2, "link": "https://www.trlibrary.com/tr/presidency",
      "blurb": "His daughter Alice marries Congressman Nicholas Longworth in a dazzling White House wedding." },
    { "year": 1906, "date": "June 8, 1906", "label": "Antiquities Act", "weight": 3, "link": "https://www.trlibrary.com/tr/conservation",
      "blurb": "Signs the Antiquities Act, giving presidents power to protect land as national monuments." },
    { "year": 1906, "date": "June 30, 1906", "label": "Pure Food & Drug Act", "weight": 3, "link": "https://www.trlibrary.com/tr/presidency",
      "blurb": "Signs the Pure Food and Drug Act and Meat Inspection Act into law." },
    { "year": 1906, "date": "September 1906", "label": "Devils Tower", "weight": 2, "link": "https://www.trlibrary.com/tr/conservation",
      "blurb": "Proclaims Devils Tower in Wyoming the nation's first national monument." },
    { "year": 1906, "date": "December 1906", "label": "Nobel Prize", "weight": 4, "link": "https://www.trlibrary.com/tr/presidency",
      "blurb": "Wins the Nobel Peace Prize for mediating the Russo-Japanese War — the first American so honored." },
    { "year": 1907, "date": "December 1907", "label": "Great White Fleet", "weight": 2, "link": "https://www.trlibrary.com/tr/presidency",
      "blurb": "Sends the Great White Fleet around the world to display American naval power." },
    { "year": 1908, "date": "January 1908", "label": "Grand Canyon", "weight": 3, "link": "https://www.trlibrary.com/tr/conservation",
      "blurb": "Protects the Grand Canyon as a national monument." },
    { "year": 1908, "date": "May 1908", "label": "Conservation Conference", "weight": 2, "link": "https://www.trlibrary.com/tr/conservation",
      "blurb": "Convenes the governors at the White House for a landmark conference on conservation." },
    { "year": 1909, "date": "March 1909", "label": "Leaves office", "weight": 2, "link": "https://www.trlibrary.com/tr/presidency",
      "blurb": "Hands the presidency to William Howard Taft and prepares to leave the country." },
    { "year": 1909, "date": "April 1909", "label": "African safari", "weight": 3, "link": "https://www.trlibrary.com/tr/post-presidency",
      "blurb": "Sets off on a year-long Smithsonian expedition through East Africa." },
    { "year": 1910, "date": "April 23, 1910", "label": "Man in the Arena", "weight": 4, "link": "https://www.trlibrary.com/tr/post-presidency",
      "blurb": "Delivers his “Citizenship in a Republic” address at the Sorbonne in Paris." },
    { "year": 1910, "date": "May 1910", "label": "Nobel lecture", "weight": 2, "link": "https://www.trlibrary.com/tr/post-presidency",
      "blurb": "Finally delivers his Nobel lecture in Christiania (Oslo), calling for a “league of peace.”" },
    { "year": 1910, "date": "June 1910", "label": "Returns from Africa", "weight": 2, "link": "https://www.trlibrary.com/tr/post-presidency",
      "blurb": "Returns to a hero's welcome in New York after a year abroad." },
    { "year": 1910, "date": "August 31, 1910", "label": "New Nationalism", "weight": 3, "link": "https://www.trlibrary.com/tr/post-presidency",
      "blurb": "Lays out his “New Nationalism” before a crowd of thirty thousand at Osawatomie, Kansas." },
    { "year": 1912, "date": "August 1912", "label": "Bull Moose party", "weight": 2, "link": "https://www.trlibrary.com/tr/post-presidency",
      "blurb": "Founds the Progressive 'Bull Moose' Party after splitting with Taft." },
    { "year": 1912, "date": "October 14, 1912", "label": "Shot campaigning", "weight": 4, "link": "https://www.trlibrary.com/tr/post-presidency",
      "blurb": "Shot in Milwaukee, he finishes his 90-minute speech with the bullet still in his chest." },
    { "year": 1912, "date": "November 1912", "label": "Loses to Wilson", "weight": 2, "link": "https://www.trlibrary.com/tr/post-presidency",
      "blurb": "Runs second to Woodrow Wilson — the best showing ever by a third-party candidate." },
    { "year": 1913, "date": "1913", "label": "Autobiography", "weight": 2, "link": "https://www.trlibrary.com/tr/post-presidency",
      "blurb": "Publishes his “Autobiography.”" },
    { "year": 1913, "date": "October 1913", "label": "Sails for the Amazon", "weight": 2, "link": "https://www.trlibrary.com/tr/post-presidency",
      "blurb": "Sails for South America to explore an uncharted river." },
    { "year": 1914, "date": "April 1914", "label": "River of Doubt", "weight": 3, "link": "https://www.trlibrary.com/tr/post-presidency",
      "blurb": "Survives a punishing descent of the Amazon's River of Doubt that nearly kills him." },
    { "year": 1916, "date": "1916", "label": "Preparedness crusade", "weight": 2, "link": "https://www.trlibrary.com/tr/post-presidency",
      "blurb": "Barnstorms the country urging military “preparedness” as war engulfs Europe." },
    { "year": 1917, "date": "1917", "label": "Sons go to war", "weight": 2, "link": "https://www.trlibrary.com/tr/post-presidency",
      "blurb": "All four Roosevelt sons serve in the World War; his own offer to raise a division is refused." },
    { "year": 1918, "date": "July 14, 1918", "label": "Quentin killed", "weight": 3, "link": "https://www.trlibrary.com/tr/post-presidency",
      "blurb": "His youngest son Quentin, a pilot, is shot down and killed over France." },
    { "year": 1919, "date": "January 6, 1919", "label": "Dies", "weight": 4, "link": "https://www.trlibrary.com/tr/legacy",
      "blurb": "Dies in his sleep at Sagamore Hill, his home on Oyster Bay, New York." },
    { "year": 1893, "date": "1893", "label": "The Wilderness Hunter", "weight": 1.5, "link": "https://www.trlibrary.com/tr/badlands",
      "blurb": "Publishes “The Wilderness Hunter,” drawing on his years in the West." },
    { "year": 1903, "date": "February 1903", "label": "Commerce & Labor Dept.", "weight": 2, "link": "https://www.trlibrary.com/tr/presidency",
      "blurb": "Creates the Department of Commerce and Labor, with a Bureau of Corporations to watch the trusts." },
    { "year": 1905, "date": "March 1905", "label": "Second inauguration", "weight": 2, "link": "https://www.trlibrary.com/tr/presidency",
      "blurb": "Inaugurated for a full term of his own." }
  ],

  "history": [
    { "year": 1858, "date": "1858", "label": "Transatlantic cable", "weight": 2,
      "blurb": "The first transatlantic telegraph cable briefly links America and Europe." },
    { "year": 1859, "date": "1859", "label": "Origin of Species", "weight": 2,
      "blurb": "Charles Darwin publishes “On the Origin of Species.”" },
    { "year": 1860, "date": "November 1860", "label": "Lincoln elected", "weight": 3,
      "blurb": "Abraham Lincoln is elected president, and Southern states begin to secede." },
    { "year": 1861, "date": "April 12, 1861", "label": "Civil War begins", "weight": 4,
      "blurb": "Confederate guns fire on Fort Sumter — Roosevelt is born into a nation at war with itself." },
    { "year": 1862, "date": "March 1862", "label": "Ironclads clash", "weight": 2,
      "blurb": "The Monitor and the Merrimack fight the first battle between ironclad warships." },
    { "year": 1862, "date": "May 1862", "label": "Homestead Act", "weight": 2,
      "blurb": "The Homestead Act opens 160-acre parcels of Western land to any settler who will farm them." },
    { "year": 1863, "date": "January 1, 1863", "label": "Emancipation", "weight": 4,
      "blurb": "Lincoln's Emancipation Proclamation declares enslaved people in rebel states to be free." },
    { "year": 1863, "date": "July 1863", "label": "Gettysburg", "weight": 3,
      "blurb": "The Battle of Gettysburg turns the tide of the Civil War." },
    { "year": 1864, "date": "November 1864", "label": "Sand Creek", "weight": 2,
      "blurb": "Colorado militia massacre a peaceful Cheyenne and Arapaho camp at Sand Creek." },
    { "year": 1865, "date": "April 9, 1865", "label": "Civil War ends", "weight": 3,
      "blurb": "Lee surrenders at Appomattox, ending four years of civil war." },
    { "year": 1865, "date": "April 14, 1865", "label": "Lincoln killed", "weight": 5,
      "blurb": "President Abraham Lincoln is assassinated at Ford's Theatre." },
    { "year": 1867, "date": "1867", "label": "Alaska purchased", "weight": 2,
      "blurb": "The United States buys Alaska from Russia." },
    { "year": 1868, "date": "1868", "label": "14th Amendment", "weight": 2,
      "blurb": "The 14th Amendment guarantees citizenship and equal protection under the law." },
    { "year": 1869, "date": "May 10, 1869", "label": "Railroad joined", "weight": 3,
      "blurb": "The first transcontinental railroad is completed at Promontory Summit, Utah." },
    { "year": 1869, "date": "November 1869", "label": "Suez Canal", "weight": 2,
      "blurb": "The Suez Canal opens, linking the Mediterranean and the Red Sea." },
    { "year": 1870, "date": "1870", "label": "15th Amendment", "weight": 2,
      "blurb": "The 15th Amendment bars denying the vote on the basis of race." },
    { "year": 1871, "date": "October 1871", "label": "Great Chicago Fire", "weight": 2,
      "blurb": "Fire destroys much of Chicago, leaving 100,000 homeless." },
    { "year": 1872, "date": "March 1, 1872", "label": "Yellowstone Park", "weight": 4,
      "blurb": "Congress creates Yellowstone, the world's first national park." },
    { "year": 1873, "date": "1873", "label": "Panic of 1873", "weight": 2,
      "blurb": "A financial panic touches off a long, deep economic depression." },
    { "year": 1876, "date": "June 25, 1876", "label": "Little Bighorn", "weight": 3,
      "blurb": "The Battle of the Little Bighorn, in the decade the West was rapidly closing." },
    { "year": 1876, "date": "1876", "label": "Telephone invented", "weight": 2,
      "blurb": "Alexander Graham Bell patents the telephone." },
    { "year": 1877, "date": "1877", "label": "Reconstruction ends", "weight": 2,
      "blurb": "The Compromise of 1877 ends Reconstruction and withdraws federal troops from the South." },
    { "year": 1879, "date": "1879", "label": "Light bulb", "weight": 2,
      "blurb": "Thomas Edison demonstrates a practical incandescent light bulb." },
    { "year": 1881, "date": "July 2, 1881", "label": "Garfield shot", "weight": 3,
      "blurb": "President James Garfield is shot; he dies that September." },
    { "year": 1881, "date": "1881", "label": "American Red Cross", "weight": 2,
      "blurb": "Clara Barton founds the American Red Cross." },
    { "year": 1882, "date": "1882", "label": "Chinese Exclusion Act", "weight": 2,
      "blurb": "Congress bars Chinese immigration — the first law to exclude a group by nationality." },
    { "year": 1883, "date": "May 24, 1883", "label": "Brooklyn Bridge", "weight": 2,
      "blurb": "The Brooklyn Bridge opens, then the longest suspension bridge in the world." },
    { "year": 1883, "date": "August 1883", "label": "Krakatoa erupts", "weight": 2,
      "blurb": "The eruption of Krakatoa is heard thousands of miles away and cools the globe." },
    { "year": 1886, "date": "May 4, 1886", "label": "Haymarket affair", "weight": 2,
      "blurb": "A labor rally in Chicago's Haymarket Square turns deadly, galvanizing the labor movement." },
    { "year": 1886, "date": "September 1886", "label": "Geronimo surrenders", "weight": 2,
      "blurb": "The Apache leader Geronimo surrenders, ending the last major Apache resistance." },
    { "year": 1886, "date": "October 28, 1886", "label": "Statue of Liberty", "weight": 3,
      "blurb": "The Statue of Liberty is dedicated in New York Harbor." },
    { "year": 1887, "date": "February 1887", "label": "Dawes Act", "weight": 2,
      "blurb": "The Dawes Act breaks up tribal lands into individual allotments." },
    { "year": 1887, "date": "1887", "label": "Interstate Commerce Act", "weight": 2,
      "blurb": "Congress creates the first federal regulatory agency to oversee the railroads." },
    { "year": 1889, "date": "April 22, 1889", "label": "Oklahoma Land Rush", "weight": 2,
      "blurb": "Settlers race to claim two million acres of newly opened land." },
    { "year": 1889, "date": "May 31, 1889", "label": "Johnstown Flood", "weight": 2,
      "blurb": "A dam failure floods Johnstown, Pennsylvania, killing more than 2,000 people." },
    { "year": 1890, "date": "July 2, 1890", "label": "Sherman Antitrust Act", "weight": 3,
      "blurb": "Congress passes the Sherman Antitrust Act — the tool Roosevelt would later wield against the trusts." },
    { "year": 1890, "date": "December 29, 1890", "label": "Wounded Knee", "weight": 3,
      "blurb": "The massacre at Wounded Knee marks the end of the Indian Wars on the Plains." },
    { "year": 1890, "date": "1890", "label": "Frontier 'closed'", "weight": 2,
      "blurb": "The Census Bureau declares the American frontier closed — the world Roosevelt found in the Badlands was already vanishing." },
    { "year": 1891, "date": "1891", "label": "Forest Reserve Act", "weight": 2,
      "blurb": "Congress lets presidents set aside forest reserves — a power Roosevelt would use lavishly." },
    { "year": 1892, "date": "1892", "label": "Ellis Island opens", "weight": 2,
      "blurb": "Ellis Island opens as the nation's main immigrant gateway." },
    { "year": 1893, "date": "1893", "label": "Chicago World's Fair", "weight": 2,
      "blurb": "The World's Columbian Exposition dazzles Chicago with the electrified “White City.”" },
    { "year": 1894, "date": "1894", "label": "Pullman Strike", "weight": 2,
      "blurb": "A national railroad strike is broken by federal troops." },
    { "year": 1896, "date": "May 1896", "label": "Plessy v. Ferguson", "weight": 2,
      "blurb": "The Supreme Court upholds “separate but equal,” entrenching segregation." },
    { "year": 1896, "date": "August 1896", "label": "Klondike Gold Rush", "weight": 2,
      "blurb": "Gold in the Klondike sets off a stampede to the Yukon." },
    { "year": 1898, "date": "February 15, 1898", "label": "USS Maine explodes", "weight": 2,
      "blurb": "The battleship Maine explodes in Havana Harbor, pushing the U.S. toward war with Spain." },
    { "year": 1898, "date": "April 1898", "label": "Spanish-American War", "weight": 3,
      "blurb": "War with Spain; the United States steps onto the world stage." },
    { "year": 1898, "date": "May 1898", "label": "Manila Bay", "weight": 2,
      "blurb": "Dewey's squadron destroys the Spanish fleet at Manila Bay in the Philippines." },
    { "year": 1898, "date": "December 1898", "label": "Treaty of Paris", "weight": 2,
      "blurb": "The Treaty of Paris ends the war; the U.S. gains Puerto Rico, Guam, and the Philippines." },
    { "year": 1900, "date": "September 1900", "label": "Galveston hurricane", "weight": 2,
      "blurb": "A hurricane destroys Galveston, Texas — the deadliest disaster in U.S. history." },
    { "year": 1901, "date": "September 6, 1901", "label": "McKinley shot", "weight": 4,
      "blurb": "President McKinley is shot in Buffalo and dies eight days later, making Roosevelt president." },
    { "year": 1903, "date": "November 1903", "label": "Panama independence", "weight": 2,
      "blurb": "Panama breaks from Colombia, clearing the way for an American canal." },
    { "year": 1903, "date": "December 17, 1903", "label": "First flight", "weight": 4,
      "blurb": "The Wright brothers make the first powered airplane flight at Kitty Hawk, North Carolina." },
    { "year": 1903, "date": "1903", "label": "First World Series", "weight": 2,
      "blurb": "Baseball crowns its first World Series champion." },
    { "year": 1906, "date": "April 18, 1906", "label": "San Francisco quake", "weight": 3,
      "blurb": "A massive earthquake and fire devastate San Francisco." },
    { "year": 1906, "date": "1906", "label": "“The Jungle”", "weight": 2,
      "blurb": "Upton Sinclair's “The Jungle” exposes the meatpacking industry and spurs food-safety laws." },
    { "year": 1907, "date": "October 1907", "label": "Panic of 1907", "weight": 2,
      "blurb": "A banking panic grips Wall Street until J.P. Morgan organizes a rescue." },
    { "year": 1908, "date": "1908", "label": "Model T", "weight": 3,
      "blurb": "Ford introduces the Model T, putting America on wheels." },
    { "year": 1909, "date": "February 1909", "label": "NAACP founded", "weight": 2,
      "blurb": "The NAACP is founded to fight for civil rights." },
    { "year": 1909, "date": "1909", "label": "North Pole reached", "weight": 2,
      "blurb": "Robert Peary's expedition claims to reach the North Pole." },
    { "year": 1911, "date": "March 1911", "label": "Triangle Fire", "weight": 2,
      "blurb": "The Triangle Shirtwaist factory fire kills 146 workers and drives workplace-safety reform." },
    { "year": 1911, "date": "1911", "label": "Standard Oil broken up", "weight": 2,
      "blurb": "The Supreme Court breaks up Standard Oil under the antitrust laws." },
    { "year": 1912, "date": "April 15, 1912", "label": "Titanic", "weight": 2,
      "blurb": "The RMS Titanic sinks on its maiden voyage across the Atlantic." },
    { "year": 1913, "date": "February 1913", "label": "Income tax", "weight": 2,
      "blurb": "The 16th Amendment establishes the federal income tax." },
    { "year": 1913, "date": "April 1913", "label": "17th Amendment", "weight": 2,
      "blurb": "The 17th Amendment gives voters, not legislatures, the power to elect U.S. senators." },
    { "year": 1913, "date": "December 1913", "label": "Federal Reserve", "weight": 2,
      "blurb": "The Federal Reserve System is created to steady the nation's banking." },
    { "year": 1914, "date": "July 28, 1914", "label": "WWI begins", "weight": 5,
      "blurb": "The First World War begins in Europe." },
    { "year": 1914, "date": "August 15, 1914", "label": "Panama Canal", "weight": 4,
      "blurb": "The Panama Canal opens — a project Roosevelt set in motion as president." },
    { "year": 1915, "date": "May 7, 1915", "label": "Lusitania sunk", "weight": 3,
      "blurb": "A German U-boat sinks the Lusitania, killing 128 Americans and inflaming opinion." },
    { "year": 1916, "date": "July 1916", "label": "The Somme", "weight": 2,
      "blurb": "The Battle of the Somme grinds on, with more than a million casualties." },
    { "year": 1916, "date": "August 1916", "label": "National Park Service", "weight": 3,
      "blurb": "Congress creates the National Park Service to care for the lands Roosevelt championed." },
    { "year": 1917, "date": "April 1917", "label": "U.S. enters WWI", "weight": 4,
      "blurb": "The United States declares war on Germany and enters the First World War." },
    { "year": 1917, "date": "November 1917", "label": "Russian Revolution", "weight": 2,
      "blurb": "The Bolsheviks seize power in Russia." },
    { "year": 1918, "date": "1918", "label": "Flu pandemic", "weight": 3,
      "blurb": "The influenza pandemic sweeps the globe, killing tens of millions." },
    { "year": 1918, "date": "November 11, 1918", "label": "WWI ends", "weight": 5,
      "blurb": "The Armistice ends the First World War." },
    { "year": 1919, "date": "January 1919", "label": "Prohibition", "weight": 2,
      "blurb": "The 18th Amendment is ratified, ushering in national Prohibition." },
    { "year": 1919, "date": "June 1919", "label": "Treaty of Versailles", "weight": 2,
      "blurb": "The Treaty of Versailles formally ends the war and remakes the map of Europe." },
    { "year": 1920, "date": "1920", "label": "Women win the vote", "weight": 3,
      "blurb": "The 19th Amendment guarantees American women the right to vote nationwide." },
    { "year": 1874, "date": "1874", "label": "Barbed wire", "weight": 1.5,
      "blurb": "Barbed wire is patented, soon fencing in the open range." },
    { "year": 1899, "date": "1899", "label": "Open Door Policy", "weight": 2,
      "blurb": "The U.S. presses an “Open Door” for trade with China." },
    { "year": 1901, "date": "December 1901", "label": "Marconi's signal", "weight": 2,
      "blurb": "Marconi sends the first transatlantic radio signal." },
    { "year": 1905, "date": "1905", "label": "Einstein's theories", "weight": 2,
      "blurb": "Einstein's “miracle year” reshapes physics with the theory of relativity." },
    { "year": 1913, "date": "December 1913", "label": "Assembly line", "weight": 2,
      "blurb": "Ford's moving assembly line transforms manufacturing." },
    { "year": 1919, "date": "February 1919", "label": "Grand Canyon N.P.", "weight": 2.5,
      "blurb": "The Grand Canyon, which Roosevelt protected as a monument, becomes a national park weeks after his death." }
  ]
};
